### ISSUE TITLE
Inference pipeline improvements

### ISSUE THREAD

**Issue by calebrob6** [fieldsoftheworld/ftw-baselines#12]
- [ ] ~~Make `download_imagery.py` a lot more robust and efficient. E.g. allow the user to pass in date ranges and an AOI. E.g. if the user passes in 2 STAC items that aren't perfectly aligned, then just download the intersection of the two (currently the script will fail). E.g. don't save intermediate results to disk when stacking the two layers.~~ (this is now in #29 )
- [x] Add model weights somewhere
- [x] Add a section to the README that shows how to download the model weights and run the above along with input/output example pictures
- [x] Integrate inference pipeline into the CLI
- [x] Add optional polygonization step to the inference pipeline
- [x] Make the inference script work with torchgeo>=0.6

**Comment by aninda-ghosh** [comment]
Model Weights added to Releases in this repository.
1. Full FTW
2. CCBY FTW

Sections added in readme to download model weights and use them for inference.

**Comment by aninda-ghosh** [comment]
https://github.com/fieldsoftheworld/ftw-baselines/pull/18 integrates the inference pipeline in the ftw cli.

**Comment by hannah-rae** [comment]
Thanks @aninda-ghosh ! @calebrob6 are the other tasks something you will plan to work on?

**Comment by cholmes** [comment]
We're close on 'Add optional polygonization step to the inference pipeline' in #19 - I'd say we should close this issue at that point and break the others out as their own issues. The first one in particular has lots of potential work in it, indeed could be several issues.

**Comment by cholmes** [comment]
#19 has progress on one of the tasks.

**Comment by m-mohr** [comment]
Closed as all tasks are checked...
