### ISSUE TITLE
Enable the ftw command-line to specify download of just a single country

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#2]
56 gigs is a lot to download - we should enable someone to just get one country and try things out. 

First step is a command to say `ftw download austria`. And then also a `ftw download all`. 

Eventually we might want to have filtering by license - `ftw download all --license-file CC-BY` or something. But that can be its own issue.

**Comment by aninda-ghosh** [comment]
Fixed this issue in PR (https://github.com/fieldsoftheworld/ftw-baselines/pull/8), for filtering by the licenses will need some changes in the code. (Need to see how that can be pulled from cloud so that it doesn't get changed in the code).
