### ISSUE TITLE
CLI command updates?

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#21]
Our current CLI hierarchy is a bit weird, and I'd like to refactor download_imagery.py to be a part of the CLI so we have a consistent interface, which makes things weirder.

`ftw download` - gets the data to run the models, etc.
`ftw unpack` - unpacks the data you downloaded
`ftw model` has three sub-commands - `fit`, `test`, and `inference`. 

The logical place to add 'download imagery' would be right next to inference, something like `ftw model download-images`, but that feels buried, and it's not really related to the inference. 

Also the top level download and unpack feel like they shouldn't be the same level as 'model', but instead should be grouped together. I also want to add the ability to download the fiboa field boundaries - see #20 (though I'm leaning towards putting that under the current download command.).

I'd like to propose a new structure:

`ftw data`, which would have `ftw data download` and `ftw data unpack`
`ftw model`, which would have `ftw model fit` and `ftw model test`
`ftw inference` which would have `ftw inference create-input` and `ftw inference run` (which would be the same as `ftw model inference` now)

We could also have `ftw inference polygonize` as its own command instead of tacked onto inference as is currently in #19. Then `--simplify` would be a bit clearer, since right now it could look like an option for the actual inference, not just the polygonization. I'm pretty sure I want to add a `--output-format` command to, so people could choose gpkg, geoparquet, geojson. And maybe a `--fiboa` flag that lets you control if you want to have it as fiboa output. 

If we do things right then we might even be able to do `ftw inference run ... | ftw inference polygonize` for people who don't care about the intermediate raster - just pipe the output from running the inference to the polygonization'.

**Comment by cholmes** [comment]
Also, any strong feelings on `--output_fn`? I was going to align these with how the fiboa cli works, which does -o and --output, since I think there's some chance some subset of people will use both tools, and it'd be nice if they worked the same. I'd also never seen the _fn thing, I thought it meant 'function' initially...

**Comment by calebrob6** [comment]
> Also, any strong feelings on --output_fn?

None whatsoever, `fn` as short for "filename" is just a habit I fell into at some point and noone has ever challenged it. Agree that it is confusing :) 

> I'm not sure what you're saying here? I think you said you liked having an independent command for polygonize. You're saying we'd have:

I'm hypothesizing that some users will just want to run the whole inference pipeline from end-to-end (instead of `ftw inference download` then `ftw inference run` then `ftw inference polygonize`) and those same users will likely not want to deal with piping outputs between calls. Other users (e.g. me) want the intermediate outputs: sentinel-2 imagery, raster predictions, final polygons. If there was a `ftw inference` call that could be used as the entry point to running all three commands in sequence, then that might be helpful.

**Comment by cholmes** [comment]
> If there was a ftw inference call that could be used as the entry point to running all three commands in sequence, then that might be helpful.

Gotcha. Oh yeah, I forgot that it's now really three calls. That makes a lot of sense, and I agree a single call with good defaults would be better than a big long piping exercise for the most common case. Let me dig into it a bit - I'm not sure about overloading the 'command group' like that - ie having `ftw inference` take arguments but also be used as the prefix for sub-commands like `ftw inference run`. May not even be possible with click.

But I take your general point - we could make a subcommand that does all three (I'm struggling for the right name - `ftw inference all` is the best I got but don't like it), or rename things (`ftw inference` does all, `ftw inf download`, `ftw inf run`, `ftw inf polygonize` I also don't like these names). I'll think about it and propose something.
