### ISSUE TITLE
Just use Sentinel 2 stac item names instead of full paths?

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#23]
Right now you have to put in the full path to planetary computer for downloading imagery for inference. I'm not even sure if using other STAC catalogs would even work, so thinking we could just require two stac item id's instead of making people put in the path?

Or perhaps have options for both, but it'd certainly be easier to be able to just put in ID's and assume PC.

**Comment by calebrob6** [comment]
Yes, a URL

**Comment by m-mohr** [comment]
Thanks, figured it out and created: https://github.com/fieldsoftheworld/ftw-baselines/pull/34 :-)
