### ISSUE TITLE
include time information in the input raster format for inference

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#26]
Using `ftw inference download` (when #25 merges) results in a file that loses all time information. If we want to do proper fiboa output and include `determination_datetime` (which we should, as it's a good best practice), we should use the time stamp of the latter satellite image. So we need to include that in the input file format in some way. It is in the STAC Item, so we just need to grab it and stick it somewhere that we can then include in the inference output and polygonization.

**Comment by m-mohr** [comment]
@cholmes Why is it the datetime of the latter image? Is it always window B? Or actually the later datetime (assuming window a and b have no particular order)?

**Comment by cholmes** [comment]
> @cholmes Why is it the datetime of the latter image? Is it always window B? Or actually the later datetime (assuming window a and b have no particular order)?

Hrm, I'm not actually sure if it's a requirement that window a and b enforce an order / make an error. We should probably check that case and either handle it or error out. But yeah, it should be the latter datetime (based on the fact determination_datetime is the last known time that you deem the boundary as accurate)

**Comment by m-mohr** [comment]
Oh, that makes sense. I can just grad the latter date from STAC then.

There's currently no check on window A before window B temporally, I think.
