### ISSUE TITLE
Improvements to make downloading imagery easier

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#29]
Right now the command to download imagery requires a user to hand select two Sentinel 2 images, and it only works on the full scene. There are a number of potential improvements to make things easier.

- [x] Add a 'bbox' parameter. Initially this would let you select a subset of the two images you selected, so you don't need to do the full scenes which could take awhile on a slower connection.
- [ ]  If the user passes in 2 STAC items that aren't perfectly aligned, then just download the intersection of the two (currently the script will fail)
- [x] #59
- [x]  Don't save intermediate results to disk when stacking the two layers.

Also related to this is #26

**Comment by m-mohr** [comment]
As discussed on the last FTW call, this issue is waiting for @snehalchaudhari98 to define a procedure how to select imagery.
