### ISSUE TITLE
Filter out holes with threshold in polygonize command

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#39]
I agree it would be nice to find a way to fill the holes - though sometimes there are real holes in a field, it would be nice to have the option (just like the area filtering).

_Originally posted by @hannah-rae in https://github.com/fieldsoftheworld/ftw-baselines/issues/31#issuecomment-2438518723_

**Comment by cholmes** [comment]
@calebrob6 also [mentioned](https://github.com/fieldsoftheworld/ftw-baselines/pull/31#discussion_r1815997140) shapely.geometry.Polygon(geom.exterior), but that would remove all holes, so would be good to see if there's a way we can just remove holes below a certain (user configured w/ default) size.

**Comment by m-mohr** [comment]
#51 optionally filters out all holes

How useful is it really to remove holes of s specific size though? It could be anything from a small bollard to a big house, all would be valid holes.

**Comment by cholmes** [comment]
I see this as just the flip side to 'simplify'. Simplify lets you remove shapes that are under X size, and defaults to about 5 pixels. And I think it's helpful even at 1 pixel - makes the output much smaller, and makes it so there's not all these little polygons that are clearly just a pixel big in the source imagery. I don't think the algorithm is really picking up a small bollard from a single pixel at this point. So I see this as more to filter out things below the threshold that you can really detect. For now 500 meters / 5 pixels seems like a good default, but then the command lets users control that if they want. If we built it off a 10 centimeter imagery product then 500 meters would be way too big, but you still may want to filter out little holes that are like 2 meters (2 pixels). 

We could just have 'simplify' both remove holes and polygons at the same size. Or we could have them be two separate commands. But yeah, I really see this as a way to filter out 'noise' where the raster isn't really resolving stuff.
