### ISSUE TITLE
Expand ftw command-line to cover all readme steps.

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#4]
It should be easy to expand the ftw cli to be the one interface to interact with things.

`python main.py fit --config configs/example_config.yaml` to `ftw fit --config`?

`python run_experiments.py` to `ftw run_experiments`

`python main.py test --config configs/example_config.yaml --trainer.devices [1] ...` to `ftw test ...`?

`python test.py --gpu 1 --checkpoint_fn logs/path...` to `ftw test ...`? 

@aninda-ghosh - feel free to claim this and try out using click. Or if you just explain the ideal commands in a comment here I can take a crack at it. And pick the names for `python main.py test` vs `python test.py`.

Hrm, also I see an `inference.py` and I don't see `run_experiments.py`.

**Comment by aninda-ghosh** [comment]
Resolved the issue in the PR (https://github.com/fieldsoftheworld/ftw-baselines/pull/8)
