### ISSUE TITLE
Speed-up CLI loading

### ISSUE THREAD

**Issue by m-mohr** [fieldsoftheworld/ftw-baselines#40]
The CLI is utterly slow, it takes a couple of seconds just to show help, which should be instant.
This is due to the case that it's always loading the AI libraries (for model/inference commands).
We should probably lazy load the commands: https://click.palletsprojects.com/en/stable/complex/#lazily-loading-subcommands

**Comment by cholmes** [comment]
Just tried this out - so much better. I also had a warning about one of the libraries that would show up with every command, and this also solved that. Great work on this, it feels blazing fast.

**Comment by m-mohr** [comment]
Oh, yeah, that's a nice side effect. Will still show up in the commands that use torch though.
