### ISSUE TITLE
Update first time user process to work with only 1 country and get to a trained model.

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#5]
The readme takes a user through the first flow of using FTW data to make an train a model, but to do that you need to wait for 56 gigabytes of data. And it also directs a user to make a custom config file.

It'd be great to have the whole flow of the readme work with only requiring people to download one country (ideally our smallest country - looks like rwanda, so they get a quicker win, especially on slow networks). They'll get crappy results, but then we can say 'try it out on all the countries, see how the model gets better'. 

#2 should enable `ftw download rwanda`. May be nice to update the notebook to make it a bit easier to select just one country, but it also works fine as it is (can just instruct people in the readme to remove all but the country they have)

And then we ideally have them just 'run' one of the existing experiments
I _think_ we need a new 'experiment' that just uses rwanda. Then we can just have the user run that experiment and see results.

And then should update the readme. Ideally we don't have anything about the custom config stuff till the end - the first flow enables any user to 'train a model'. Second step perhaps is downloading all the data and fully training a 'baseline model', and then perhaps we have a tutorial on making a new config and doing experimentation.

**Comment by aninda-ghosh** [comment]
https://github.com/fieldsoftheworld/ftw-baselines/pull/8

Resolved this issue in this PR

**Comment by aninda-ghosh** [comment]
We need to think how a way to use a default config to just train for a country. Maybe one country becomes default for the entire dataset. @hannah-rae  any suggestion which country this can be?

**Comment by m-mohr** [comment]
This is also of importance for the tests #38

**Comment by m-mohr** [comment]
I tried it with Rwanda, but the fitting process leads to an error:

> [rank0]: RuntimeError: It looks like your LightningModule has parameters that were not used in producing the loss returned by training_step. If this is intentional, you must enable the detection of unused parameters in DDP, either by setting the string value `strategy='ddp_find_unused_parameters_true'` or by setting the flag in the strategy with `strategy=DDPStrategy(find_unused_parameters=True)`.

**Comment by cholmes** [comment]
Yeah, I think the importance of this goes down now that we have pre-trained models. I really wanted to give a new user the experience of using a model, and have that not take tons of time. But I think the new user flow now is to just use a pre trained model, and does seem like anyone interested in experimenting probably should get the full dataset, not just a subset. 

So we can close this, esp if we have some version of this for the tests.
