### ISSUE TITLE
Fail to download data

### ISSUE THREAD

**Issue by csyhy1986** [fieldsoftheworld/ftw-baselines#69]
Downloading checksum.md5...
Error downloading https://data.source.coop/kerner-lab/fields-of-the-world-archive/checksum.md5: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'data.source.coop'. (_ssl.c:1000)>
Failed to download checksum.md5 file.

**Comment by m-mohr** [comment]
Hey,

Thanks for reporting. Which operating system and version are you using? Which Python version are you using?

Also, please make sure your local root SSL certificates are up to date etc. I guess that's the issue because it works for most other people afaik.

**Comment by csyhy1986** [comment]
> Hey,
> 
> Thanks for reporting. Which operating system and version are you using? Which Python version are you using?
> 
> Also, please make sure your local root SSL certificates are up to date etc.
> 
> It works for most other people afaik so I have to assume an issue with your specific environment for now.

Thanks very much for your response, now it works for me. Close this issue.
